language: c
compiler: gcc
sudo: false

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - g++-7
      - clang-format-6.0

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - mkdir build && cd build/
  - cmake .. && make
  - ./myexample
