#travis configuration for testing
language: c


install:
- cd ${TRAVIS_BUILD_DIR}

before_script: 
- cd ${TRAVIS_BUILD_DIR}


# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}


after_success:
- cd ${TRAVIS_BUILD_DIR}
