language: c
compiler: gcc
sudo: false

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-7
      - clang-format-5.0

script:
  - run-clang-format.py -r main.c
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - mkdir build && cd build/
  - cmake .. && make
  - ./myexample
