version: 2.1
executors:
  exectr:
    docker:
      - image: willallves/continuous_integration_4_project:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            cmake .
            make
      - persist_to_workspace:
          root: .
          paths: build

      # Clang-format sources check
      - run: |
          apt-get update -y
          apt-get install -y clang-format-3.8
          ln -s /usr/bin/clang-format-3.8 /usr/bin/clang-format
          SOURCE_FILES=`find ./ -name \*.c -type f -or -name \*.h -type f`
          for SOURCE_FILE in $SOURCE_FILES
          do
            export FORMATTING_ISSUE_COUNT=`clang-format -output-replacements-xml $SOURCE_FILE | grep offset | wc -l`
            if [ "$FORMATTING_ISSUE_COUNT" -gt "0" ]; then
              echo "Source file $SOURCE_FILE contains formatting issues. Please use clang-format tool to resolve found issues."
              exit 1
            fi
          done

  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build/bin
            ./myexample
      - store_test_results:
          path: build/bin/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
