version: 2.1
executors:
  exectr:
    docker:
      - image: willallves/continuous_integration_4_project:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            cmake .
            make
      - persist_to_workspace:
          root: .
          paths: build

  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build/bin
            ./myexample
      - store_test_results:
          path: build/bin/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
