version: 2.1

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            cmake .
            make
      - persist_to_workspace:
          root: .
          paths: build


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
